In [1]:
import numpy as np

# array

In [5]:
x=np.arange(3,10,0.1)
x

array([3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2,
       4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5,
       5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8,
       6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1,
       8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4,
       9.5, 9.6, 9.7, 9.8, 9.9])

In [9]:
x=np.zeros((2,3))
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
x=np.ones((5,6),float)
x

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [20]:
x=np.linspace(1,2,10)
x

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [21]:
x=np.indices((4,5))
x

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

# Generating array from text

In [23]:
from io import StringIO

In [25]:
data="1, 2, 3, 4\n 5, 6, 7, 8"
x=np.genfromtxt(StringIO(data),delimiter=',')
x

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [29]:
np.genfromtxt(StringIO(data), delimiter=",", dtype="|U5", autostrip=True)

array([['1', '2', '3', '4'],
       ['5', '6', '7', '8']], dtype='<U5')

# Quickstart

In [32]:
x=np.arange(15).reshape(3,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
x.ndim

2

In [34]:
x.shape


(3, 5)

In [35]:
x.size

15

In [39]:
x.dtype

dtype('int32')

In [40]:
x.item

<function ndarray.item>

In [41]:
x.size

15

In [42]:
x.data

In [43]:
x.itemsize

4

In [44]:
a=[1,2,3,4,5,6,7,8]
x=np.array(a)
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [45]:
x[0]

1

In [47]:
x[7]

8

In [48]:
x[-2]

7

In [50]:
a=[1,2,3,4,5,6,7,8]
x=np.array([a,a])
x

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [56]:
a=[1,2,3,4,5,6,7,8]
x=np.array([a,a])
print(x)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [57]:
x-x

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [58]:
x/x

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [59]:
x*x

array([[ 1,  4,  9, 16, 25, 36, 49, 64],
       [ 1,  4,  9, 16, 25, 36, 49, 64]])

In [61]:
x**x

array([[       1,        4,       27,      256,     3125,    46656,
          823543, 16777216],
       [       1,        4,       27,      256,     3125,    46656,
          823543, 16777216]], dtype=int32)

In [62]:
x>2

array([[False, False,  True,  True,  True,  True,  True,  True],
       [False, False,  True,  True,  True,  True,  True,  True]])

In [63]:
x.sum()

72

In [64]:
x.min()

1

In [66]:
x.max()

8

In [67]:
x.sum(axis=0)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [68]:
x.sum(axis=1)

array([36, 36])

In [70]:
x.cumsum(axis=1)

array([[ 1,  3,  6, 10, 15, 21, 28, 36],
       [ 1,  3,  6, 10, 15, 21, 28, 36]], dtype=int32)

In [72]:
x[0]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [73]:
a=[1,2,3,4,5,6,7,8]
x=np.array(a)
print(x)

[1 2 3 4 5 6 7 8]


In [74]:
x[2]

3

In [75]:
x[2:3]

array([3])

In [77]:
x[:6:2]=-100
x

array([-100,    2, -100,    4, -100,    6,    7,    8])

In [6]:
import numpy as np

In [17]:
a=[1,2,3,4,5,6,7,8]
x=np.array([a,a,a,a,a,a,a])
print(x)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [20]:
x[1:3,:]

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [21]:
x[1,...]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
for a in x.flat:
    print(a)

1
2
3
4
5
6
7
8
1
2
3
4
5
6
7
8
1
2
3
4
5
6
7
8
1
2
3
4
5
6
7
8
1
2
3
4
5
6
7
8
1
2
3
4
5
6
7
8
1
2
3
4
5
6
7
8


In [28]:
x.shape

(7, 8)

In [29]:
x.reshape(8,7)

array([[1, 2, 3, 4, 5, 6, 7],
       [8, 1, 2, 3, 4, 5, 6],
       [7, 8, 1, 2, 3, 4, 5],
       [6, 7, 8, 1, 2, 3, 4],
       [5, 6, 7, 8, 1, 2, 3],
       [4, 5, 6, 7, 8, 1, 2],
       [3, 4, 5, 6, 7, 8, 1],
       [2, 3, 4, 5, 6, 7, 8]])

In [31]:
x.T

array([[1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8]])

In [32]:
x.T.shape

(8, 7)

In [33]:
x.reshape(4,14)

array([[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6],
       [7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4],
       [5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2],
       [3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]])

In [38]:
a=x.flat
print(a[6])

7


In [42]:
print(np.vstack((x,x)))

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [43]:
np.hstack((x,x))

array([[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]])

In [44]:
x.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6,
       7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4,
       5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
np.hsplit(x,2)

[array([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]),
 array([[5, 6, 7, 8],
        [5, 6, 7, 8],
        [5, 6, 7, 8],
        [5, 6, 7, 8],
        [5, 6, 7, 8],
        [5, 6, 7, 8],
        [5, 6, 7, 8]])]